escape_patterns = [[{"LOWER": "so"}, {"LOWER": "far"}, {"LOWER": "as"}, {"LOWER": "is"}, {"LOWER": "possible"}],
                   [{"LOWER": "as"}, {"LOWER": "possible"}],
                   [{"LOWER": "as"}, {"LOWER": "little"}, {"LOWER": "as"}, {"LOWER": "possible"}],
                   [{"LOWER": "where"}, {"LOWER": "possible"}],
                   [{"LOWER": "as"}, {"LOWER": "much"}, {"LOWER": "as"}, {"LOWER": "possible"}],
                   [{"LOWER": "if"}, {"LOWER": "it"}, {"LOWER": "should"}, {"LOWER": "prove"}, {"LOWER": "necessary"}],
                   [{"LOWER": "to"}, {"LOWER": "the"}, {"LOWER": "extant"}, {"LOWER": "necessary"}],
                   [{"LOWER": "as"}, {"LOWER": "appropriate"}],
                   [{"LOWER": "as"}, {"LOWER": "required"}],
                   [{"LOWER": "to"}, {"LOWER": "the"}, {"LOWER": "extant"}, {"LOWER": "practical"}],
                   [{"LOWER": "if"}, {"LOWER": "practicable"}],
                   [{"LOWER": "as"}, {"LOWER": "necessary"}],
                   [{"LOWER": "if"}, {"LOWER": "necessary"}],
                   [{"LOWER": "if"}, {"LOWER": "possible"}]]