vague_term_patterns = [[{"LOWER": "some"}],
                       [{"LOWER": "any"}],
                       [{"LOWER": "allowable"}],
                       [{"LOWER": "several"}],
                       [{"LOWER": "many"}],
                       [{"LOWER": "a"}, {"LOWER": "lot"}, {"LOWER": "of"}],
                       [{"LOWER": "a"}, {"LOWER": "few"}],
                       [{"LOWER": "almost"}, {"LOWER": "always"}],
                       [{"LOWER": "very"}, {"LOWER": "nearly"}],
                       [{"LOWER": "about"}],
                       [{"LOWER": "close"}, {"LOWER": "to"}],
                       [{"LOWER": "almost"}],
                       [{"LOWER": "approximate"}],
                       [{"LOWER": "ancillary"}],
                       [{"LOWER": "relevant"}],
                       [{"LOWER": "routine"}],
                       [{"LOWER": "common"}],
                       [{"LOWER": "typical"}],
                       [{"LOWER": "routine"}],
                       [{"LOWER": "generic"}],
                       [{"LOWER": "flexible"}],
                       [{"LOWER": "expandable"}],
                       [{"LOWER": "sufficient"}],
                       [{"LOWER": "adequate"}],
                       [{"LOWER": "appropriate"}],
                       [{"LOWER": "efficient"}],
                       [{"LOWER": "secure"}],
                       [{"LOWER": "effective"}],
                       [{"LOWER": "proficient"}],
                       [{"LOWER": "reasonable"}],
                       [{"LOWER": "customary"}]]